# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=250)),
                ('picture_subject', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('is_active', models.BooleanField()),
                ('friends', models.ManyToManyField(related_name='_profile_friends_+', to='imager_profile.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
