# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 03:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20160411_0307'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
