# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=250)),
                ('album_description', models.TextField()),
                ('alb_date_uploaded', models.DateField(auto_now=True)),
                ('alb_date_modified', models.DateField(auto_now_add=True)),
                ('alb_date_published', models.DateField(auto_now_add=True)),
                ('published', models.CharField(choices=[('Private', 'Private'), ('Shared', 'Shared'), ('Public', 'Public')], default='Public', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_title', models.CharField(max_length=250)),
                ('image_description', models.TextField()),
                ('date_uploaded', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now_add=True)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('published', models.CharField(choices=[('Private', 'Private'), ('Shared', 'Shared'), ('Public', 'Public')], default='Public', max_length=7)),
            ],
        ),
    ]
