# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0002_auto_20160411_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='ablums',
            new_name='albums',
        ),
    ]
